#swagger:
#  title: 梦学谷博客系统接口文档
#  description: 梦学谷博客系统—用户&角色&菜单接口
#  exclude-path: /error # 剔除请求
#
#server:
#  port: 8003
#  servlet:
#    context-path: /system
#
#spring:
#  redis:
#    host: manage.kaiyu.work # Redis服务器地址
#    port: 6379 # Redis服务器连接端口
#    # Redis 服务器连接密码（默认为空），注释放到上面来，不然控制台可能会一直打印日志
#    password:
#  application:
#    name: system-server # 应用名
#  # 数据源配置
#  datasource:
#    username: root
#    password: LYY&css1314
#    url: jdbc:mysql://kaiyu.work:3306/WMS?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#    #mysql8版本以上驱动包指定新的驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
#    initialSize: 8
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#
#mybatis-plus:
#  type-aliases-package: com.kaiyu.devops.entities
#  # xxxMapper.xml 路径
#  mapper-locations: classpath*:com/kaiyu/devops/system/mapper/**/*.xml
#
## 日志级别，会打印sql语句
#logging:
#  level:
#    com.mengxuegu.blog.system.mapper: info
