server:
  port: 10011
spring:
  application:
    name: develop
  cloud:
    alibaba:
      seata:
        tx-service-group: wms_group #统一事务组
    #注册进nacos
#    nacos:
#      discovery:
#        server-addr: 219.135.168.199:8848 #注册中心地址
  redis:
    database: 1
    host: 219.135.168.199
    port: 12580
    timeout: 10000
    password: 9527
    lettuce:
      pool:
        max-active: 30 #最大连接数
        max-wait: -1 #连接池最大等待时间(负数表示没有限制)
        max-idle: 10 #连接池最大空闲数
        min-idle: 2 #连接池最小空闲数
        timeout: 60000 #连接超时时间
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://kaiyu.work:3306/WMS?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: LYY&css1314
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    druid:
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 # 验证连接是否可用，使用的SQL语句
      testWhileIdle: true  #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testOnBorrow: false  #借出连接时不要测试，否则很影响性能
      testOnReturn: false
#配置mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  page:
    helperDialect: mysql
    countSql: true
    reasonable: true
    pageSizeZero: false

#openFeign配置
#openFeign配置
feign:
  httpclient:
    connection-timeout: 60000
    enabled: true
  sentinel:
    enabled: true
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#日志级别
logging:
  level:
    io:
      seata: info
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
